services:
  app:
    container_name: hng_video_suite_java
    build: .
    image: hng_video_suite_java

    ports:
      - 8383:8383
    env_file:
      - ./.env
    environment:
      - SPRING_CONFIG_LOCATION=/app/config/application.properties
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    volumes:
      - ./src/main/resources/application.properties:/app/config/application.properties
    networks:
      - hng_boilerplate_java_web_staging-backend-net

networks:
  hng_boilerplate_java_web_staging-backend-net:
    external: true